name: Code verification

on:
  [ workflow_dispatch, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
         args: check --config .github/workflows/ruff.toml
