name: Code verification

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      with:
        args: check --config .github/workflows/ruff.toml