name: Release publication

on:
  release:
    types: [published]

jobs:
  minify_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python and Minifier
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - run: pip install python-minifier

      - name: Run the minifier on numclick.py
      - run: pyminify numclick.py --output numclick-mini.py --rename-globals

      - name: Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            numclick.py
            numclick-mini.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}