name: Release publication

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  minify_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
        
      - name: Install python-minifier  
        run: pip install python-minifier

      - name: Run the minifier on numclick.py
        run: pyminify numclick.py --output numclickmini.py --rename-globals --prefer-single-line --remove-literal-statements

      - name: Upload Asset
        uses: softprops/action-gh-release@v3
        with:
          files: |
            numclick.py
            numclickmini.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
